# Generated by Django 4.0.6 on 2022-07-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Arthur', max_length=200),
        ),
    ]
